# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c7c2199dc959256d3837d3b79513cd4c236c8a318780e918487a27f092d8942647b17bca0edb877eb9f80a70eb7642639bbfb56100065c4435b124a9405d60
  linkedin_key: 755robx1dkk6ew
  linkedin_secret: NralgYDYzEmFZrGy
  google_client_id: 947568070205-4n22kckvs64rqjsvpu2n3nvm4dkkffss.apps.googleusercontent.com
  google_client_secret: zTsMFuT0Jky3Kxe0g2HN_wbg

test:
  secret_key_base: 4decfd547838c4887d7d9787bf7f9f88fb051fcb99d40ed70379e42e68e324e228acce4b541b31bc4b7de6399a3693fb3487d78020e18bd0a222494af893729d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
